### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by Egorand** [JakeWharton/adb-event-mirror#15]
Wanna be able to do `brew install adb-event-mirror`.

**Comment by JakeWharton** [comment]
Yeah I was talking to Matt about this. Probably going to set up my own tap since I don't want to bother with homebrew-core.

**Comment by jrodbx** [comment]
Would this still compile the script on demand (I think you mentioned this in your internal demo) after brew installing or instead install precompiled executable jars?

**Comment by JakeWharton** [comment]
Prefer to keep the script for simplicity. Not having a build system is nice! I should add a `--test` flag or something...

**Comment by JakeWharton** [comment]
```
brew install JakeWharton/repo/adb-event-mirror
```
